apiVersion: apps/v1
kind: Deployment
metadata:
  name: session-queue
spec:
  replicas: 3
  selector:
    matchLabels:
      app: session-queue
  template:
    metadata:
      labels:
        app: session-queue
    spec:
      containers:
        - name: session-queue
          image: session-queue:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: session-queue-config
            - secretRef:
                name: session-queue-secret
          resources:
            requests:
              memory: 128Mi
              cpu: 100m
            limits:
              memory: 256Mi
              cpu: 500m
          livenessProbe:
            httpGet:
              path: /livez
              port: 3000
            initialDelaySeconds: 2
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /readyz
              port: 3000
            initialDelaySeconds: 2
            periodSeconds: 5

---

apiVersion: v1
kind: Service
metadata:
  name: session-queue
spec:
  selector:
    app: session-queue
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: NodePort
